[tool.poetry]
name = "itly.plugin-schema-validator"
version = "0.1.6"
description = "Iteratively Analytics SDK - Schema Validator Plugin"
readme="README.md"
authors = ["Iteratively"]
license = "MIT"
packages = [
    { include = "itly" }
]

[tool.poetry.dependencies]
python = "^3.6"
jsonschema = "^3.2.0"
"itly.sdk" = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
